### ISSUE TITLE
the channel don't mismatch???

### ISSUE THREAD

**Issue by DRACOyu** [WangYQ9/VideoReID_PSTA#3]
Traceback (most recent call last):
 File "Train.py", line 315, in <module>
  main()
File "Train.py", line 169, in main
    train(model, trainloader, xent, tent, optimizer, use_gpu)
File "Train.py", line 200, in train
     outputs, features = model(imgs)

File "VideoReID_PSTA-main/models/PSTA.py", line 114, in forward
     feat_map_1 = self.layer1(feat_map)

File "VideoReID_PSTA-main/models/STAM.py", line 66, in forward
    gap_feat_map0 = self.TRAG(feat_map, reshape_map, feat_vect, embed_feat)

File "VideoReID_PSTA-main/models/TRA.py", line 121, in forward
    Gs_joint0 = self.gg_temporal(Gs_joint0)

RuntimeError: Given groups=1, weight of size 128 256 1 1, expected input[16, 360, 18, 10] to have 256 channels, but got 360 channels instead

**Comment by WangYQ9** [comment]
Sorry for I use of the wrong data preprocessing. 
I just update 'Train.py'. 
Now the channel mismatch problem is fixed.
